from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parent.parent
PROJECT_ROOT = SKILL_ROOT.parents[2]
REFERENCE_PATH = SKILL_ROOT / "references" / "automation-ids.md"
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
sys.path.insert(0, str(PROJECT_ROOT))

from PySide6.QtWidgets import QApplication  # noqa: E402

from mybot_ui.app_v2 import MainWindow, NewApiImportDialog, ReplyPolicyDialog  # noqa: E402
from mybot_ui.reply_policy import ReplyPolicy  # noqa: E402


def collect() -> tuple[list[dict[str, str]], list[str]]:
    app = QApplication.instance() or QApplication([])
    windows = [
        MainWindow(),
        NewApiImportDialog(),
        ReplyPolicyDialog(ReplyPolicy(), ["Automation Probe"]),
    ]
    errors: list[str] = []
    records: dict[str, dict[str, str]] = {}
    try:
        app.processEvents()
        for window in windows:
            manager = window.automation_ids
            manager.refresh()
            report = manager.audit()
            for category in ("missing", "invalid", "duplicates"):
                errors.extend(f"{type(window).__name__} {category}: {item}" for item in report[category])
            for item in manager.inventory():
                records[item["automation_id"]] = item
    finally:
        for window in reversed(windows):
            window.close()
        app.processEvents()
    return sorted(records.values(), key=lambda item: item["automation_id"]), errors


def render(records: list[dict[str, str]]) -> str:
    lines = [
        "# MyBot AutomationId Inventory",
        "",
        "Generated by `scripts/audit_automation_ids.py --write`. Do not edit the table manually.",
        "",
        "All operable Qt controls use the `MyBot.<Window>.<semantic_name>` namespace. Dynamic MCP and Skill toggles use their extension ID instead of a row number.",
        "",
        "| AutomationId | Qt class |",
        "| --- | --- |",
    ]
    for item in records:
        lines.append(f"| `{item['automation_id']}` | `{item['class']}` |")
    lines.extend(
        [
            "",
            "## Tray Boundary",
            "",
            "The Windows Shell owns the notification-area icon; locate it by tooltip `MyBot2`. The Qt tray menu and actions carry `MyBot.Tray.menu`, `MyBot.Tray.show_action`, `MyBot.Tray.restart_action`, and `MyBot.Tray.close_action` markers where the provider exposes Qt properties.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit MyBot UI AutomationIds.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Validate IDs and the generated inventory.")
    mode.add_argument("--write", action="store_true", help="Regenerate the inventory reference.")
    args = parser.parse_args()

    records, errors = collect()
    expected = render(records)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    if args.write:
        REFERENCE_PATH.write_text(expected, encoding="utf-8")
        print(f"Wrote {len(records)} AutomationIds to {REFERENCE_PATH}")
        return 0
    if args.check and (
        not REFERENCE_PATH.is_file()
        or REFERENCE_PATH.read_text(encoding="utf-8") != expected
    ):
        print("AutomationId inventory is stale; run with --write.", file=sys.stderr)
        return 1
    print(f"Validated {len(records)} unique MyBot AutomationIds.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
